In [97]:
import numpy as np
import time
import matplotlib.pylab as plt
%pylab inline

Populating the interactive namespace from numpy and matplotlib


C:\Users\swink_000\Anaconda2\envs\py36\lib\site-packages\IPython\core\magics\pylab.py:161: UserWarning: pylab import has clobbered these variables: ['linspace', 'plt']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


### Вопрос 1

Создайте numpy.ndarray и продемонстрируйте различные способы обращения по индексам

In [21]:
x = np.random.randint(low = 0, high = 100, size = (3,4,2))
print ('Исходный массив:')
print (x)

print ('Обращение к второму элементу в первой строке: ', x[0,0,1])
print ('Обращение к первой строке: ', x[0,:].tolist())
print ('Обращение к первому столбцу: ', x[:,0])
print ('Слайс массива(первые элементы двумерных массивов каждой строчки с 2 по 3 столбец): ', 
                           x[:,1:3,0].tolist())

Исходный массив:
[[[86 74]
  [ 5 88]
  [61 77]
  [18  7]]

 [[32 73]
  [98 92]
  [68 81]
  [27 44]]

 [[36 56]
  [71 99]
  [15 30]
  [57 74]]]
Обращение к второму элементу в первой строке:  74
Обращение к первой строке:  [[86, 74], [5, 88], [61, 77], [18, 7]]
Обращение к первому столбцу:  [[86 74]
 [32 73]
 [36 56]]
Слайс массива(первые элементы двумерных массивов каждой строчки с 2 по 3 столбец):  [[5, 61], [98, 68], [71, 15]]


### Вопрос 2

Сравните по производительности numpy.array и list выполняя стандартную операцию.

In [31]:
npArray = np.random.randint(low = 0, high = 10000, size = 4096)
listArray = list(np.random.randint(low = 0, high = 10000, size = 4096))

In [67]:
#let's find max value in npArray
timeArray = []
for _ in range(1000):
    time1 = time.time()
    npArray = np.random.randint(low = 0, high = 10000, size = 4096)
    x = npArray.max()
    time2 = time.time()
    timeArray.append(time2 - time1)
    
print ('Time taken: ', np.mean(timeArray))

Time taken:  0.0002501730918884277


In [69]:
#let's find max value in listArray
timeArray = []
for _ in range(1000):
    time1 = time.time()
    listArray = [np.random.randint(low = 0, high = 10000) for _ in range(4096)]
    x = max(listArray)
    time2 = time.time()
    timeArray.append(time2 - time1)
    
print ('Time taken: ', np.mean(listArray))

Time taken:  5079.9560546875


Видно, что время затрачиваемое на генерацию и нахождение максимума очень сильно отличается

### Вопрос 3

С помощью list comprehension написать numpy.linspace(), проверим на эффективность

In [98]:
start = 0
finish = 10000000
N = 100000

In [107]:
#проверим на эффективность linspace
timeArray1 = []
for N in range(2, 10000):
    time1 = time.time()
    linspace = np.linspace(start, finish, N)
    time2 = time.time()
    timeArray1.append(time2 - time1)

print ('Time taken: ', np.mean(timeArray1))

Time taken:  0.00013141346874416388


In [108]:
#проверим на эффективность list Comprehension
timeArray2 = []
for N in range(2, 10000):
    time1 = time.time()
    listLinspace = [start + finish/(N-1) * i for i in range(N)]
    time2 = time.time()
    timeArray2.append(time2 - time1)

print ('Time taken: ', np.mean(timeArray2))

Time taken:  0.004370575834450947


В этом случае также, numpy гораздо эффективнее.